services:
- type: web
  name: wordpress
  env: docker
  plan: standard
  autoDeploy: false
  disk:
    name: wordpress
    mountPath: /var/www/html
    sizeGB: 20
  envVars:
 # PostgreSQL service
- key: dpg-cq2ois56l47c73bb017g-a
  fromDatabase:
    name: postgresql-db
    property: connectionString

    
- databases:
  # A Pro database instance with a read replica
  - name: dpg-cq2ois56l47c73bb017g-a # Required
    postgresMajorVersion: "16" # Default: most recent supported version
    region: ohio # Default: oregon
    plan: free # Default: starter
    databaseName: prod # Default: generated value based on name
    user: client # Default: generated value based on name
    ipAllowList: []
